# Generated by Django 4.2.10 on 2024-03-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_topic_question_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="cost",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
