# Generated by Django 4.2.10 on 2024-03-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_user_preferred_language_user_query_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(
                choices=[("pt-br", "Portugues")], default="pt-br", max_length=5
            ),
        ),
    ]
