# Generated by Django 4.2.10 on 2024-03-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_user_preferred_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="doc_balance",
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(upload_to=""),
        ),
    ]
