# Generated by Django 4.2.10 on 2024-03-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_user_doc_balance_alter_document_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(upload_to="docs/"),
        ),
    ]
