# Generated by Django 4.2.11 on 2024-03-17 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_document_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentBody",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doc", models.BinaryField()),
                ("type", models.CharField(max_length=100)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.document",
                    ),
                ),
            ],
        ),
    ]
