# Generated by Django 4.2.11 on 2024-04-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_document_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
