# Generated by Django 4.2.11 on 2024-04-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_document_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                blank=True, default="OK", max_length=255, null=True
            ),
        ),
    ]
