# Generated by Django 4.2.11 on 2024-04-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_document_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(default="OK", max_length=255),
        ),
    ]
