# Generated by Django 4.2.11 on 2024-04-09 15:20

from django.db import migrations


def populate_user_from_topic(apps, schema_editor):
    Question = apps.get_model("core", "Question")
    for question in Question.objects.filter(user__isnull=True):
        question.user = question.topic.user
        question.save()


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0014_question_user_topic_publish_user_query_credits_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(populate_user_from_topic),
    ]
