# Generated by Django 4.2.11 on 2024-04-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_topicinvitesent"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="type",
            field=models.CharField(
                choices=[
                    ("ge", "Geral"),
                    ("es", "Estudos"),
                    ("jr", "Jurídico"),
                    ("sa", "Saúde"),
                    ("ci", "Ciência"),
                    ("tc", "Tecnologia"),
                    ("nr", "Normas"),
                ],
                default="ge",
                max_length=2,
            ),
        ),
    ]
