# Generated by Django 4.2.11 on 2024-04-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_topic_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="doc_balance",
        ),
        migrations.AlterField(
            model_name="topic",
            name="type",
            field=models.CharField(
                choices=[
                    ("ge", "Geral"),
                    ("es", "Estudos"),
                    ("jr", "Jurídico"),
                    ("sa", "Medicina e Saúde"),
                    ("ci", "Ciência"),
                    ("tc", "Tecnologia"),
                    ("nr", "Normas"),
                ],
                default="ge",
                max_length=2,
            ),
        ),
    ]
