# Generated by Django 4.2.11 on 2024-04-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_remove_user_doc_balance_alter_topic_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
