# Generated by Django 4.2.11 on 2024-04-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_document_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="vector_db",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(default="--", max_length=255),
        ),
    ]
